-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "1.1",
})

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal = "kitty"
local fileManager = "nemo"
local menu = "hyprlauncher"
local browser = "firefox"
local editor = "code-oss"

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function()
	hl.exec_cmd("dms run >/dev/null 2>&1")
	-- hl.exec_cmd("nwg-dock-hyprland -x -d -i 48 -p bottom")
	-- cinnamon-schema-mirror (mirrors org.gnome.desktop.interface ->
	-- org.cinnamon.desktop.interface live, so Nemo picks up theme changes
	-- without needing a restart) runs as its own systemd --user service now,
	-- not launched from here -- it kept dying under `dms restart` (which uses
	-- loginctl and appears to affect more than just its own process), and a
	-- plain setsid-detached exec_cmd here has no supervision to recover from
	-- that. systemd's Restart=always does. See
	-- ~/.config/systemd/user/cinnamon-schema-mirror.service.
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
-- Border colors used to be hardcoded here (omarchy-style shared active/inactive
-- vars). They're now supplied by require("dms.colors") below instead, which is
-- regenerated by matugen on every theme switch and calls hl.config({general=
-- {col=...}, group=...}) itself -- see ~/.config/hypr/dms/colors.lua.

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 20,

		border_size = 2,

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing = false,

		layout = "master",
	},

	decoration = {
		rounding = 0,
		rounding_power = 2,

		-- Change transparency of focused and unfocused windows
		active_opacity = 0.9,
		inactive_opacity = 0.8,

		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = 0xee1a1a1a,
		},

		blur = {
			enabled = true,
			size = 6,
			passes = 2,
			vibrancy = 0.1,
		},
	},

	animations = {
		enabled = true,
	},
})

-- XWayland doesn't support fractional scaling natively, so at this monitor's
-- 1.2 scale, XWayland clients (e.g. Spotify, which is forced onto XWayland
-- via --ozone-platform=x11 since its native Wayland backend is broken) render
-- at a mismatched scale — blurry text, garbled/corrupted layout. This forces
-- XWayland to render at 1x and lets Hyprland upscale the buffer instead.
hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 8, bezier = "easeInOutCubic" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 20, bezier = "linear", style = "loop" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		preserve_split = true, -- You probably want this
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
	master = {
		new_status = "master",
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
		enable_swallow = true,
		swallow_regex = "^(kitty)$",
	},
})

---------------
---- INPUT ----
---------------

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		follow_mouse = 1,

		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		touchpad = {
			natural_scroll = true,
		},
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-------------------------------------------------
---- APPS (omarchy: default/hypr/bindings/applications.lua) ----
-------------------------------------------------
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal), { description = "Terminal" })
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd(fileManager), { description = "File manager" })
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd(fileManager), { description = "File manager" })
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd(browser), { description = "Browser" })
hl.bind(
	mainMod .. " + SHIFT + ALT + B",
	hl.dsp.exec_cmd(browser .. " --private-window"),
	{ description = "Browser (private)" }
)
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd(editor), { description = "Editor" })
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu), { description = "App launcher (hyprlauncher)" })
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("thunderbird"), { description = "Email" })
hl.bind(
	mainMod .. " + Z",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"),
	{ description = "Exit Hyprland" }
)

--------------------------------------------------------
---- TILING (omarchy: default/hypr/bindings/tiling.lua) ----
--------------------------------------------------------
hl.bind(mainMod .. " + W", hl.dsp.window.close(), { description = "Close window" })
local closeWindowBind = hl.bind(mainMod .. " + Q", hl.dsp.window.close(), { description = "Close window" })
-- closeWindowBind:set_enabled(false)

hl.bind(mainMod .. " + P", hl.dsp.window.pseudo(), { description = "Pseudo window" })
hl.bind(
	mainMod .. " + ALT + SPACE",
	hl.dsp.window.float({ action = "toggle" }),
	{ description = "Toggle window floating/tiling" }
)
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }), { description = "Full screen" })
hl.bind(mainMod .. " + ALT + F", hl.dsp.window.fullscreen({ mode = "maximized" }), { description = "Full width" })
hl.bind(mainMod .. " + J", hl.dsp.layout("swapprev"), { description = "Swap to previous window (master)" })
hl.bind(mainMod .. " + K", hl.dsp.layout("swapnext"), { description = "Swap to next window (master)" })
hl.bind(mainMod .. " + I", hl.dsp.layout("orientationtop"), { description = "Master orientation: top" })
hl.bind(mainMod .. " + O", hl.dsp.layout("orientationcenter"), { description = "Master orientation: center" })
hl.bind(mainMod .. " + U", hl.dsp.layout("orientationleft"), { description = "Master orientation: left" })

-- Switch to a submap called `resize`.
hl.bind("ALT + mouse:272", hl.dsp.submap("resize"), { mouse = true, description = "Resize window (drag)" })

-- Start a submap called "resize".
hl.define_submap("resize", function()
	-- Set repeating binds for resizing the active window.
	hl.bind(
		"D",
		hl.dsp.window.resize({ x = 10, y = 0, relative = true }),
		{ repeating = true, description = "Grow width" }
	)
	hl.bind(
		"A",
		hl.dsp.window.resize({ x = -10, y = 0, relative = true }),
		{ repeating = true, description = "Shrink width" }
	)
	hl.bind(
		"W",
		hl.dsp.window.resize({ x = 0, y = 10, relative = true }),
		{ repeating = true, description = "Grow height" }
	)
	hl.bind(
		"S",
		hl.dsp.window.resize({ x = 0, y = -10, relative = true }),
		{ repeating = true, description = "Shrink height" }
	)

	-- Use `reset` to go back to the global submap
	hl.bind("escape", hl.dsp.submap("reset"), { description = "Exit resize mode" })
end)

-- Keybinds further down will be global again...

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }), { description = "Focus on left window" })
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }), { description = "Focus on right window" })
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }), { description = "Focus on above window" })
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }), { description = "Focus on below window" })

-- Swap window position in the given direction (omarchy: SUPER + SHIFT + arrow)
hl.bind(
	mainMod .. " + SHIFT + left",
	hl.dsp.window.swap({ direction = "l" }),
	{ description = "Swap window to the left" }
)
hl.bind(
	mainMod .. " + SHIFT + right",
	hl.dsp.window.swap({ direction = "r" }),
	{ description = "Swap window to the right" }
)
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.swap({ direction = "u" }), { description = "Swap window up" })
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.swap({ direction = "d" }), { description = "Swap window down" })

-- Move the whole workspace to the monitor in the given direction
hl.bind(
	mainMod .. " + SHIFT + ALT + left",
	hl.dsp.workspace.move({ monitor = "l" }),
	{ description = "Move workspace to left monitor" }
)
hl.bind(
	mainMod .. " + SHIFT + ALT + right",
	hl.dsp.workspace.move({ monitor = "r" }),
	{ description = "Move workspace to right monitor" }
)
hl.bind(
	mainMod .. " + SHIFT + ALT + up",
	hl.dsp.workspace.move({ monitor = "u" }),
	{ description = "Move workspace to up monitor" }
)
hl.bind(
	mainMod .. " + SHIFT + ALT + down",
	hl.dsp.workspace.move({ monitor = "d" }),
	{ description = "Move workspace to down monitor" }
)

-- Window grouping (tabbed windows)
hl.bind(mainMod .. " + G", hl.dsp.group.toggle(), { description = "Toggle window grouping" })
hl.bind(
	mainMod .. " + ALT + G",
	hl.dsp.window.move({ out_of_group = true }),
	{ description = "Move active window out of group" }
)
hl.bind(
	mainMod .. " + ALT + left",
	hl.dsp.window.move({ into_group = "l" }),
	{ description = "Move window to group on left" }
)
hl.bind(
	mainMod .. " + ALT + right",
	hl.dsp.window.move({ into_group = "r" }),
	{ description = "Move window to group on right" }
)
hl.bind(
	mainMod .. " + ALT + up",
	hl.dsp.window.move({ into_group = "u" }),
	{ description = "Move window to group on top" }
)
hl.bind(
	mainMod .. " + ALT + down",
	hl.dsp.window.move({ into_group = "d" }),
	{ description = "Move window to group on bottom" }
)
hl.bind(mainMod .. " + CTRL + left", hl.dsp.group.prev(), { description = "Move grouped window focus left" })
hl.bind(mainMod .. " + CTRL + right", hl.dsp.group.next(), { description = "Move grouped window focus right" })

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
-- Move it there silently (without following) with mainMod + SHIFT + ALT + [0-9]
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }), { description = "Switch to workspace " .. i })
	hl.bind(
		mainMod .. " + SHIFT + " .. key,
		hl.dsp.window.move({ workspace = i }),
		{ description = "Move window to workspace " .. i }
	)
	hl.bind(
		mainMod .. " + SHIFT + ALT + " .. key,
		hl.dsp.window.move({ workspace = i, follow = false }),
		{ description = "Move window silently to workspace " .. i }
	)
end

-- Cycle workspaces (omarchy: TAB / SHIFT+TAB / CTRL+TAB)
hl.bind(mainMod .. " + TAB", hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace" })
hl.bind(mainMod .. " + SHIFT + TAB", hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace" })
hl.bind(mainMod .. " + CTRL + TAB", hl.dsp.focus({ workspace = "previous" }), { description = "Former workspace" })

-- Cycle windows on screen (omarchy: ALT+TAB) and monitors (omarchy: CTRL+ALT+TAB)
hl.bind("ALT + TAB", hl.dsp.window.cycle_next(), { description = "Focus on next window" })
hl.bind("ALT + SHIFT + TAB", hl.dsp.window.cycle_next({ next = false }), { description = "Focus on previous window" })
hl.bind("CTRL + ALT + TAB", hl.dsp.focus({ monitor = "+1" }), { description = "Focus on next monitor" })
hl.bind("CTRL + ALT + SHIFT + TAB", hl.dsp.focus({ monitor = "-1" }), { description = "Focus on previous monitor" })

-- Scratchpad (omarchy names this special workspace "scratchpad")
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("scratchpad"), { description = "Toggle scratchpad" })
hl.bind(
	mainMod .. " + SHIFT + S",
	hl.dsp.window.move({ workspace = "special:scratchpad" }),
	{ description = "Move window to scratchpad" }
)
hl.bind(
	mainMod .. " + ALT + S",
	hl.dsp.window.move({ workspace = "special:scratchpad", follow = false }),
	{ description = "Move window to scratchpad (silently)" }
)
hl.bind(mainMod .. " + grave", hl.dsp.workspace.toggle_special("scratchpad"), { description = "Toggle scratchpad" })
hl.bind(
	mainMod .. " + SHIFT + grave",
	hl.dsp.window.move({ workspace = "special:scratchpad", follow = false }),
	{ description = "Move window to scratchpad (silently)" }
)

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(
	mainMod .. " + mouse_down",
	hl.dsp.focus({ workspace = "e+1" }),
	{ description = "Scroll active workspace forward" }
)
hl.bind(
	mainMod .. " + mouse_up",
	hl.dsp.focus({ workspace = "e-1" }),
	{ description = "Scroll active workspace backward" }
)

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true, description = "Move window" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Resize window" })

-- Keyboard-driven resize (omarchy: SUPER/SUPER+ALT/SUPER+CTRL + code:20/21, the bracket keys)
hl.bind(
	mainMod .. " + code:20",
	hl.dsp.window.resize({ x = -100, y = 0, relative = true }),
	{ description = "Expand window left" }
)
hl.bind(
	mainMod .. " + code:21",
	hl.dsp.window.resize({ x = 100, y = 0, relative = true }),
	{ description = "Shrink window left" }
)
hl.bind(
	mainMod .. " + SHIFT + code:20",
	hl.dsp.window.resize({ x = 0, y = -100, relative = true }),
	{ description = "Shrink window up" }
)
hl.bind(
	mainMod .. " + SHIFT + code:21",
	hl.dsp.window.resize({ x = 0, y = 100, relative = true }),
	{ description = "Expand window down" }
)
hl.bind(
	mainMod .. " + ALT + code:20",
	hl.dsp.window.resize({ x = -25, y = 0, relative = true }),
	{ description = "Expand window left a little" }
)
hl.bind(
	mainMod .. " + ALT + code:21",
	hl.dsp.window.resize({ x = 25, y = 0, relative = true }),
	{ description = "Shrink window left a little" }
)
hl.bind(
	mainMod .. " + CTRL + code:20",
	hl.dsp.window.resize({ x = -300, y = 0, relative = true }),
	{ description = "Expand window left a lot" }
)
hl.bind(
	mainMod .. " + CTRL + code:21",
	hl.dsp.window.resize({ x = 300, y = 0, relative = true }),
	{ description = "Shrink window left a lot" }
)

----------------------------------------------------------
---- UTILITIES (omarchy: default/hypr/bindings/utilities.lua) ----
---- Wired to DMS's shell IPC in place of omarchy-menu/omarchy-shell ----
----------------------------------------------------------
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("dms ipc call launcher toggle"), { description = "App launcher" })
-- Note: DMS's "bar toggle" IPC function takes a (selector, value) pair whose
-- expected values aren't documented/discoverable via the CLI, so this omarchy
-- bind (SUPER+SHIFT+SPACE toggles the top bar) is left unwired rather than
-- shipped guessing at broken arguments.
hl.bind(
	mainMod .. " + CTRL + SPACE",
	hl.dsp.exec_cmd("dms ipc call dash toggle wallpaper"),
	{ description = "Wallpaper picker" }
)
hl.bind(mainMod .. " + CTRL + T", hl.dsp.exec_cmd("qs -n -c themeswitcher"), { description = "Theme switcher" })
hl.bind(
	mainMod .. " + CTRL + SHIFT + SPACE",
	hl.dsp.exec_cmd("qs -n -c themeswitcher"),
	{ description = "Theme switcher" }
)
hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd("dms ipc call powermenu toggle"), { description = "System menu" })
hl.bind(mainMod .. " + CTRL + P", hl.dsp.exec_cmd("dms ipc call powermenu toggle"), { description = "Power menu" })
hl.bind(mainMod .. " + CTRL + L", hl.dsp.exec_cmd("dms ipc call lock lock"), { description = "Lock system" })
hl.bind(
	mainMod .. " + CTRL + V",
	hl.dsp.exec_cmd("dms ipc call clipboard toggle"),
	{ description = "Clipboard manager" }
)
hl.bind(mainMod .. " + CTRL + N", hl.dsp.exec_cmd("dms ipc call night toggle"), { description = "Toggle nightlight" })
hl.bind(
	mainMod .. " + CTRL + I",
	hl.dsp.exec_cmd("dms ipc call inhibit toggle"),
	{ description = "Toggle locking on idle" }
)
-- omarchy binds SUPER+K to its keybindings cheatsheet, but K is already taken
-- here by master-layout swapnext (see TILING section), so this uses SUPER+SHIFT+K
-- instead, opening DMS's own built-in cheatsheet (dms keybinds show hyprland),
-- which auto-reads every bind above from this config, description text included.
hl.bind(
	mainMod .. " + SHIFT + K",
	hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"),
	{ description = "Keybindings cheatsheet" }
)

-- DMS consolidates bluetooth/network/audio/display into one control-center
-- panel, unlike omarchy's four separate bar panels, so all four omarchy keys
-- point at the same panel here.
hl.bind(
	mainMod .. " + CTRL + A",
	hl.dsp.exec_cmd("dms ipc call control-center toggle"),
	{ description = "Control center (audio)" }
)
hl.bind(
	mainMod .. " + CTRL + B",
	hl.dsp.exec_cmd("dms ipc call control-center toggle"),
	{ description = "Control center (bluetooth)" }
)
hl.bind(
	mainMod .. " + CTRL + W",
	hl.dsp.exec_cmd("dms ipc call control-center toggle"),
	{ description = "Control center (network)" }
)
hl.bind(
	mainMod .. " + CTRL + D",
	hl.dsp.exec_cmd("dms ipc call control-center toggle"),
	{ description = "Control center (display)" }
)

-- Notifications
hl.bind(
	mainMod .. " + comma",
	hl.dsp.exec_cmd("dms ipc call notifications dismissAllPopups"),
	{ description = "Dismiss notifications" }
)
hl.bind(
	mainMod .. " + SHIFT + comma",
	hl.dsp.exec_cmd("dms ipc call notifications clearAll"),
	{ description = "Clear all notifications" }
)
hl.bind(
	mainMod .. " + CTRL + comma",
	hl.dsp.exec_cmd("dms ipc call notifications toggleDoNotDisturb"),
	{ description = "Toggle do not disturb" }
)

-- Screenshot / color picker (omarchy uses its own omarchy-capture-* scripts;
-- this system has hyprshot + hyprpicker instead)
hl.bind("PRINT", hl.dsp.exec_cmd("hyprshot -m region"), { description = "Screenshot" })
hl.bind(mainMod .. " + PRINT", hl.dsp.exec_cmd("pkill hyprpicker || hyprpicker -a"), { description = "Color picker" })

------------------------------------------------------
---- MEDIA (omarchy: default/hypr/bindings/media.lua) ----
------------------------------------------------------
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	{ locked = true, repeating = true, description = "Volume up" }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	{ locked = true, repeating = true, description = "Volume down" }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, description = "Mute" }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, description = "Mute microphone" }
)
hl.bind(
	"XF86MonBrightnessUp",
	hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),
	{ locked = true, repeating = true, description = "Brightness up" }
)
hl.bind(
	"XF86MonBrightnessDown",
	hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),
	{ locked = true, repeating = true, description = "Brightness down" }
)

-- Precise volume/brightness (omarchy: ALT + media key)
hl.bind(
	"ALT + XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+"),
	{ locked = true, repeating = true, description = "Volume up precise" }
)
hl.bind(
	"ALT + XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"),
	{ locked = true, repeating = true, description = "Volume down precise" }
)
hl.bind(
	"ALT + XF86MonBrightnessUp",
	hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 1%+"),
	{ locked = true, repeating = true, description = "Brightness up precise" }
)
hl.bind(
	"ALT + XF86MonBrightnessDown",
	hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 1%-"),
	{ locked = true, repeating = true, description = "Brightness down precise" }
)

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true, description = "Next track" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "Pause" })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "Play" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true, description = "Previous track" })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },

	move = "20 monitor_h-120",
	float = true,
})

-- Float Firefox/Thunderbird child windows (downloads, dialogs, popups,
-- notifications) while leaving the main browser/mail window tiled. Both
-- apps' main window title always contains their app name ("Mozilla Firefox" /
-- "Mozilla Thunderbird"); every child window has some other title, so a
-- negative-lookahead on title is what tells them apart. Rules are static and
-- only ever evaluated against a window's *initial* class/title.
hl.window_rule({
	name = "float-firefox-children",
	match = { class = "^firefox$", title = "negative:Mozilla Firefox" },

	float = true,
})

hl.window_rule({
	name = "float-thunderbird-children",
	match = { class = "^org\\.mozilla\\.Thunderbird$", title = "negative:Mozilla Thunderbird" },

	float = true,
})

-- DMS Include Configs
require("dms.layout")
require("dms.cursor")
require("dms.colors")

require("dms-theme-sync")
