# Generated by matugen -- do not edit manually.
# cmatrix only supports named ANSI colors via -C, not hex, hence `cmatrix_color`
# in the colorscheme toml (falls back to green, cmatrix's own default) instead
# of deriving one from the theme's primary hex.
function cmatrix
    command cmatrix -C {{cmatrix_color}} $argv
end
